### ISSUE TITLE
List of plans

### ISSUE THREAD

**Issue by ybbjegj** [smocean/sphinxjs#4]
+ *0.2.x*
    -* [x]  1. gulp-minify-css 替换为 gulp-clean-css
* [x]  2. cli 支持增量编译
* [ ]  3. 代码内嵌时编译不中断
* [x]  4. cli 支持 help
* [x]  5. 支持 liftoff
* [ ]  6. Browsersync 深度配置

* [ ]  7. 错误提醒发送 email
* [x]  8. cli clean 功能
* [ ]  9. 优化资源定位 支持 domain	
* [x]  10. sass 支持 sourcemap 及 cli 可配置
* [ ]  11. Browsersync 开启多端口 多实例
* [ ]  12. es6 语法可配置
* [ ]  13. 增加 cache
* [ ]  14. 脚手架
* [ ]  15. 文档开发
* [ ]  16. cli es6 可配置
* [ ]  17. 支持代码检测

**Comment by fengnana** [comment]
**Task:** `#8`
